name: x_bee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^6.0.3
  dartz: ^0.10.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  permission_handler: ^11.0.1 
  mobile_scanner: ^7.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
