// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32mahsvr_FKDEeWa56B4BBr4uymSQXGA',
    appId: '1:565072016641:web:c37b03efbde40323541700',
    messagingSenderId: '565072016641',
    projectId: 'beehelperdemo',
    authDomain: 'beehelperdemo.firebaseapp.com',
    databaseURL: 'https://beehelperdemo.firebaseio.com',
    storageBucket: 'beehelperdemo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbrHXclNtLQk6ozxmDirm8haugE1ML6Bw',
    appId: '1:565072016641:android:5b14a4939dda2471541700',
    messagingSenderId: '565072016641',
    projectId: 'beehelperdemo',
    databaseURL: 'https://beehelperdemo.firebaseio.com',
    storageBucket: 'beehelperdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpF2XB2ixk0PJmbnoldCOVX-CCnw18QM',
    appId: '1:565072016641:ios:43a142acae700ebe541700',
    messagingSenderId: '565072016641',
    projectId: 'beehelperdemo',
    databaseURL: 'https://beehelperdemo.firebaseio.com',
    storageBucket: 'beehelperdemo.firebasestorage.app',
    androidClientId: '565072016641-r6o5fn5sk5v83okdcb21kbke134ci0t6.apps.googleusercontent.com',
    iosClientId: '565072016641-l1fdbbrqo8fd2s0en9i81i5qh8qb7m4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.xBee',
  );
}
